services:
  api:
    image: 'biserinka-api'
    build:
      context: .
    container_name: api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    ports:
      - "8080:8080"
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"